/home/user/miniconda/envs/py36/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
  0%|                                                                                                                                                                                | 0/10 [00:00<?, ?it/s] 10%|████████████████▊                                                                                                                                                       | 1/10 [00:12<01:52, 12.55s/it] 20%|█████████████████████████████████▌                                                                                                                                      | 2/10 [00:13<01:13,  9.16s/it] 30%|██████████████████████████████████████████████████▍                                                                                                                     | 3/10 [00:15<00:48,  6.90s/it] 40%|███████████████████████████████████████████████████████████████████▏                                                                                                    | 4/10 [00:17<00:32,  5.38s/it] 50%|████████████████████████████████████████████████████████████████████████████████████                                                                                    | 5/10 [00:18<00:21,  4.23s/it] 60%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                   | 6/10 [00:19<00:13,  3.28s/it] 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                  | 7/10 [00:21<00:08,  2.76s/it] 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 8/10 [00:23<00:04,  2.43s/it] 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 9/10 [00:24<00:02,  2.17s/it]100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:26<00:00,  2.00s/it]100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:26<00:00,  2.63s/it]
| [0m 1       [0m | [0m-182.8   [0m | [0m 0.3753  [0m | [0m 0.6483  [0m |
[34m[1mwandb[0m: [32m[41mERROR[0m Attempted to change value of key "lr_ac" from 0.3753256340122696 to 0.00011293619186222453
[34m[1mwandb[0m: [32m[41mERROR[0m If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (0.00011293619186222453, 0.2721062920429295)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_ac_mcc.py", line 249, in <module>
    n_iter=10,
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 174, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 112, in probe
    self._space.probe(params)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/target_space.py", line 194, in probe
    target = self.target_func(**params)
  File "main_ac_mcc.py", line 85, in main
    config.lr_ac = lr_ac
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/wandb/wandb_config.py", line 217, in __setitem__
    key, val = self._sanitize(key, val)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/wandb/wandb_config.py", line 233, in _sanitize
    key, self._items[key], val))
wandb.wandb_config.ConfigError: Attempted to change value of key "lr_ac" from 0.3753256340122696 to 0.00011293619186222453
If you really want to do this, pass allow_val_change=True to config.update()
